[project]
name = "order-service"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.20.0",
    "asyncpg>=0.31.0",
    "dependency-injector>=4.49.1",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "pydantic-settings>=2.15.0",
    "sqlalchemy[asyncio]>=2.1.1",
    "uvicorn[standard]>=0.54.0",
]

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pre-commit>=4.6.2",
    "ruff>=0.16.9",
]

[tool.ruff]
extend-exclude = ["alembic/versions"]
force-exclude = true

[tool.ruff.lint.isort]
known-third-party = ["alembic", "fastapi"]

[tool.mypy]
exclude = ["alembic/"]
explicit_package_bases = true
plugins = ["pydantic.mypy"]
