"""add outbox destination

Revision ID: e4a64e5827b9
Revises: f946fa431d42
Create Date: 2026-09-30 12:32:49.392883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4a64e5827b9'
down_revision: Union[str, Sequence[str], None] = 'f946fa431d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox', sa.Column('destination', sa.String(), nullable=False, server_default='order_events'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox', 'destination')
    # ### end Alembic commands ###
